spring:
  datasource:
    username: ${env.DATABASE_USERNAME}
    url: ${env.DATABASE_URL}
    password: ${env.DATABASE_PASSWORD}
  http:
    multipart:
      max-request-size: 11MB
      max-file-size: 10MB
  jackson:
    serialization:
      fail-on-empty-beans: "false"
  jpa:
    hibernate:
      ddl-auto: update
      logging:
        show-sql: true
    properties:
      hibernate:
        format_sql: true
